apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
spec:
  type: NodePort
  selector:
    app: impulse-music
  ports:
      - nodePort: 31000
        protocol: TCP
        port: 3000
