apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-preview
spec:
  type: LoadBalancer
  selector:
    app: impulse-music  
  ports:
      - protocol: TCP
        port: 8089
        targetPort: 3000
